package com.au.repository;

import java.util.HashMap;
import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;
import com.au.model.EmployeeDetailsHistory;

@Transactional
@Repository
public interface EmployeeDetailsHistoryRepository extends JpaRepository<EmployeeDetailsHistory, Integer>{
	
	@Query(value = "SELECT * from employee_details_history edh where edh.emp_id=?1 And "
			+ "edh.active=true order by edh.created_date desc limit 1 ",nativeQuery = true)
	public EmployeeDetailsHistory employeeDetailsHistoryOnEmpId(Integer emp_id);
	
	@Query(value=" select * from employee_details_history where empcode=:empCode order by created_date desc limit 1 ",nativeQuery = true)
	public EmployeeDetailsHistory getLatestEmployeeDetails(@Param("empCode") String empCode);

	@Modifying
	@Query(value = "update EmployeeDetailsHistory edh set edh.active=false where edh.emp_history_id=?1")
	public void delete1(Integer id);
	
	@Modifying
	@Query(value = "update EmployeeDetailsHistory edh set edh.active=true where edh.emp_history_id=?1")
	public void delete2(Integer id);

	
	@Query(value = "select new map(edh.emp_history_id as emp_history_id,edh.job_id as job_id,edh.empcode as empcode,edh.employee_name as employee_name,"
			+ "edh.designation_id as designation_id,edh.date_of_joining as date_of_joining,edh.email as email,edh.employee_name as employee_name,"
			+ "edh.grosspay_ctc as grosspay_ctc,edh.ctc as ctc,edh.gender as gender,edh.employee_status as employee_status,edh.created_date as created_date,"
			+ "sc.school_name_short as school_name_short,d.dept_name_short as dept_name_short,edh.net_pay as net_pay,edh.bank_id as bank_name,"
			+ "edh.created_by as created_by,edh.created_username as created_username,edh.active as active,edh.master_code as master_code,"
			+ "edh.empcode as empcode,edh.firstname as firstname,edh.lastname as lastname,edh.report_id as report_id,"
			+ "edh.mobile as mobile,edh.alt_mobile_no as alt_mobile_no,edh.dateofbirth as dateofbirth,edh.martial_status as martial_status,edh.blood_group as blood_group,"
			+ "edh.father_name as father_name,edh.current_location as current_location,edh.salary_structure_id as salary_structure_id,"
			+ "edh.ctc as ctc,edh.pf_no as pf_no,edh.pan_no as pan_no,edh.emp_type_id as emp_type_id,edh.job_type_id as job_type_id,"
			+ "edh.hometown as hometown,edh.pincode as pincode,edh.annual_salary as annual_salary,edh.spl_pay as spl_pay,"
			+ "edh.key_skills as key_skills,edh.bank_account_no as bank_account_no,edh.bank_branch as bank_branch,edh.bank_ifsccode as bank_ifsccode,"
			+ "edh.leave_approver1_emp_id as leave_approver1_emp_id,edh.leave_approver2_emp_id as leave_approver2_emp_id,edh.attach as attach,edh.dlno as dlno,edh.dlexpno as dlexpno,"
			+ "edh.passportno as passportno,edh.passportexpno as passportexpnow,edh.bankacc2 as bankacc2,edh.to_date as to_date,edh.prob as prob,"
			+ "edh.nda as nda,edh.nca as nca,edh.uan_no as uan_no,edh.punched_card_status as punched_card_status,edh.photo as photo,edh.maternity_status as maternity_status,"
			+ "edh.marriage_status as marriage_status,edh.paternity_status as paternity_status,edh.salary_approve_status as salary_approve_status,"
			+ "edh.new_join_status as new_join_status,edh.pf_status as pf_status,"
			+ "edh.pt_status as pt_status,edh.permanant_file as permanant_file,edh.aadhar as aadhar,edh.photo_upload_status as photo_upload_status,edh.proctor_assign_status as proctor_assign_status,"
			+ "edh.bank_account_holder_name as bank_account_holder_name,edh.grosspay_ctc as grosspay_ctc,edh.nda_nca_attach as nda_nca_attach,edh.store_indent_approver1 as store_indent_approver1,"
			+ "edh.store_indent_approver2 as store_indent_approver2,edh.esi_no as esi_no,edh.hra as hra,edh.da as da,edh.cca as cca,edh.net_pay as net_pay,"
			+ "edh.other_allow as other_allow,edh.spl_1 as spl_1,edh.title as title,edh.caste_category as caste_category,"
			+ "edh.school as school,edh.contract_empcode as contract_empcode,edh.consolidated_amount as consolidated_amount,edh.from_date as from_date,edh.date_of_joining as date_of_joining,edh.remarks as remarks,"
			+ "edh.subject_skills as subject_skills,edh.employee_status as employee_status,edh.proctor_type as proctor_type,ss.salary_structure as salary_structure,dg.designation_short_name as designation_short_name,"
			+ "emt.empTypeShortName as empTypeShortName,edh1.employee_name as leave_approver1_name,edh2.employee_name as leave_approver2_name,"
			+ "edh.job_short_name as jobShortName,edh.dept_name_short as deptNameShort,edh.school_name_short as schoolNameShort,edh.shift_name as UpdateShiftName,"
			+ "edh.leave_approver1_name as updatedLeave_approver1_name,edh.leave_approver2_name as updatedLeave_approver2_name,"
			+ "edh.chief_proctor_id as chief_proctor_id,edh.religion as religion,edh.preferred_name_for_email as preferred_name_for_email,sh.shiftName as shiftName,jt.job_short_name as job_short_name) from EmployeeDetailsHistory edh "
			+ "left join Schools sc on edh.school_id=sc.school_id "
			+ "left join Department d on edh.dept_id=d.dept_id "
			+ "left join Shift sh on edh.shift_category_id=sh.shiftCategoryId "
			+ "left join JobType jt on edh.job_type_id=jt.job_type_id "
			+ "left join EmployeeType emt on edh.emp_type_id=emt.empTypeId "
			+ "left join SalaryStructure ss on edh.salary_structure_id=ss.salary_structure_id "
			+ "left join Designation dg on edh.designation_id=dg.designation_id "
			+ "left join EmployeeDetails edh1 on edh.emp_id=edh1.leave_approver1_emp_id "
			+ "left join EmployeeDetails edh2 on edh.emp_id=edh2.leave_approver2_emp_id "
			+ "where edh.active=true And CONCAT(IfNull(edh1.empcode,''),'',IfNull(edh1.employee_name,''),'',IfNull(edh1.preferred_name_for_email,''),' ',"
			+ "IfNull(edh1.email,''),'',IfNull(sc.school_name_short,''),'',IfNull(d.dept_name_short,'')) LIKE %?1% ")
	public Page<Object> getAllDataFilteredByKeyword(Pageable pageable, Object keyword); 
	
	@Query(value = "select new map(edh.emp_history_id as emp_history_id,edh.job_id as job_id,edh.empcode as empcode,edh.employee_name as employee_name,"
			+ "edh.designation_id as designation_id,edh.date_of_joining as date_of_joining,edh.email as email,edh.employee_name as employee_name,"
			+ "edh.grosspay_ctc as grosspay_ctc,edh.ctc as ctc,edh.gender as gender,edh.employee_status as employee_status,edh.created_date as created_date,"
			+ "sc.school_name_short as school_name_short,d.dept_name_short as dept_name_short,edh.net_pay as net_pay,edh.bank_id as bank_name,"
			+ "edh.created_by as created_by,edh.created_username as created_username,edh.active as active,edh.master_code as master_code,"
			+ "edh.empcode as empcode,edh.firstname as firstname,edh.lastname as lastname,edh.report_id as report_id,"
			+ "edh.mobile as mobile,edh.alt_mobile_no as alt_mobile_no,edh.dateofbirth as dateofbirth,edh.martial_status as martial_status,edh.blood_group as blood_group,"
			+ "edh.father_name as father_name,edh.current_location as current_location,edh.salary_structure_id as salary_structure_id,"
			+ "edh.ctc as ctc,edh.pf_no as pf_no,edh.pan_no as pan_no,edh.emp_type_id as emp_type_id,edh.job_type_id as job_type_id,"
			+ "edh.hometown as hometown,edh.pincode as pincode,edh.annual_salary as annual_salary,edh.spl_pay as spl_pay,"
			+ "edh.key_skills as key_skills,edh.bank_account_no as bank_account_no,edh.bank_branch as bank_branch,edh.bank_ifsccode as bank_ifsccode,"
			+ "edh.leave_approver1_emp_id as leave_approver1_emp_id,edh.leave_approver2_emp_id as leave_approver2_emp_id,edh.attach as attach,edh.dlno as dlno,edh.dlexpno as dlexpno,"
			+ "edh.passportno as passportno,edh.passportexpno as passportexpnow,edh.bankacc2 as bankacc2,edh.to_date as to_date,edh.prob as prob,"
			+ "edh.nda as nda,edh.nca as nca,edh.uan_no as uan_no,edh.punched_card_status as punched_card_status,edh.photo as photo,edh.maternity_status as maternity_status,"
			+ "edh.marriage_status as marriage_status,edh.paternity_status as paternity_status,edh.salary_approve_status as salary_approve_status,"
			+ "edh.new_join_status as new_join_status,edh.pf_status as pf_status,"
			+ "edh.pt_status as pt_status,edh.permanant_file as permanant_file,edh.aadhar as aadhar,edh.photo_upload_status as photo_upload_status,edh.proctor_assign_status as proctor_assign_status,"
			+ "edh.bank_account_holder_name as bank_account_holder_name,edh.grosspay_ctc as grosspay_ctc,edh.nda_nca_attach as nda_nca_attach,edh.store_indent_approver1 as store_indent_approver1,"
			+ "edh.store_indent_approver2 as store_indent_approver2,edh.esi_no as esi_no,edh.hra as hra,edh.da as da,edh.cca as cca,edh.net_pay as net_pay,"
			+ "edh.other_allow as other_allow,edh.spl_1 as spl_1,edh.title as title,edh.caste_category as caste_category,"
			+ "edh.school as school,edh.contract_empcode as contract_empcode,edh.consolidated_amount as consolidated_amount,edh.from_date as from_date,edh.date_of_joining as date_of_joining,edh.remarks as remarks,"
			+ "edh.subject_skills as subject_skills,edh.employee_status as employee_status,edh.proctor_type as proctor_type,ss.salary_structure as salary_structure,dg.designation_short_name as designation_short_name,"
			+ "emt.empTypeShortName as empTypeShortName,edh1.employee_name as leave_approver1_name,edh2.employee_name as leave_approver2_name,"
			+ "edh.job_short_name as jobShortName,edh.dept_name_short as deptNameShort,edh.school_name_short as schoolNameShort,edh.shift_name as UpdateShiftName,"
			+ "edh.leave_approver1_name as updatedLeave_approver1_name,edh.leave_approver2_name as updatedLeave_approver2_name,"
			+ "edh.chief_proctor_id as chief_proctor_id,edh.religion as religion,edh.preferred_name_for_email as preferred_name_for_email,sh.shiftName as shiftName,jt.job_short_name as job_short_name) from EmployeeDetailsHistory edh "
			+ "left join Schools sc on edh.school_id=sc.school_id "
			+ "left join Department d on edh.dept_id=d.dept_id "
			+ "left join Shift sh on edh.shift_category_id=sh.shiftCategoryId "
			+ "left join JobType jt on edh.job_type_id=jt.job_type_id "
			+ "left join EmployeeType emt on edh.emp_type_id=emt.empTypeId "
			+ "left join SalaryStructure ss on edh.salary_structure_id=ss.salary_structure_id "
			+ "left join Designation dg on edh.designation_id=dg.designation_id "
			+ "left join EmployeeDetails edh1 on edh.emp_id=edh1.leave_approver1_emp_id "
			+ "left join EmployeeDetails edh2 on edh.emp_id=edh2.leave_approver2_emp_id")
	public Page<Object> getAllSortedData(Pageable pageable);

	@Query(value = "SELECT edh from EmployeeDetailsHistory edh where edh.active=true")
	public List<EmployeeDetailsHistory> findAll11();
	
	@Query(value = "select new map(emp_history_id AS id,"
			+ "    emp_id AS emp_id,"
			+ "    school_id AS school_id,"
			+ "    dept_id AS dept_id,"
			+ "    job_id AS job_id,"
			+ "    email AS email,"
			+ "    employee_name AS employee_name,"
			+ "    created_date AS created_date,"
			+ "    created_by AS created_by,"
			+ "    created_username AS created_username,"
			+ "    active AS active,"
			+ "    master_code AS master_code,"
			+ "    empcode AS empcode,"
			+ "    firstname AS firstname,"
			+ "    lastname AS lastname,"
			+ "    report_id AS report_id,"
			+ "    mobile AS mobile,"
			+ "    alt_mobile_no AS alt_mobile_no,"
			+ "    dateofbirth AS dateofbirth,"
			+ "    martial_status AS martial_status,"
			+ "    blood_group AS blood_group,"
			+ "    designation_id AS designation_id,"
			+ "    father_name AS father_name,"
			+ "    spouse_name AS spouse_name,"
			+ "    current_location AS current_location,"
			+ "    salary_structure_id AS salary_structure_id,"
			+ "    ctc AS ctc,"
			+ "    pf_no AS pf_no,"
			+ "    pan_no AS pan_no,"
			+ "    emp_type_id AS emp_type_id,"
			+ "    job_type_id AS job_type_id,"
			+ "    hometown AS hometown,"
			+ "    pincode AS pincode,"
			+ "    annual_salary AS annual_salary,"
			+ "    spl_pay AS spl_pay,"
			+ "    key_skills AS key_skills,"
			+ "    bank_id AS bank_id,"
			+ "    bank_account_no AS bank_account_no,"
			+ "    bank_branch AS bank_branch,"
			+ "    bank_ifsccode AS bank_ifsccode,"
			+ "    leave_approver1_emp_id AS leave_approver1_emp_id,"
			+ "    leave_approver2_emp_id AS leave_approver2_emp_id,"
			+ "    attach AS attach,"
			+ "    dlno AS dlno,"
			+ "    dlexpno AS dlexpno,"
			+ "    passportno AS passportno,"
			+ "    passportexpno AS passportexpno,"
			+ "    bankacc2 AS bankacc2,"
			+ "    to_date AS to_date,"
			+ "    prob AS prob,"
			+ "    nda AS nda,"
			+ "    nca AS nca,"
			+ "    uan_no AS uan_no,"
			+ "    punched_card_status AS punched_card_status,"
			+ "    photo AS photo,"
			+ "    shift_category_id AS shift_category_id,"
			+ "    gender AS gender,"
			+ "    maternity_status AS maternity_status,"
			+ "    marriage_status AS marriage_status,"
			+ "    paternity_status AS paternity_status,"
			+ "    salary_approve_status AS salary_approve_status,"
			+ "    new_join_status AS new_join_status,"
			+ "    pf_status AS pf_status,"
			+ "    pt_status AS pt_status,"
			+ "    permanant_file AS permanant_file,"
			+ "    aadhar AS aadhar,"
			+ "    photo_upload_status AS photo_upload_status,"
			+ "    proctor_assign_status AS proctor_assign_status,"
			+ "    bank_account_holder_name AS bank_account_holder_name,"
			+ "    grosspay_ctc AS grosspay_ctc,"
			+ "    nda_nca_attach AS nda_nca_attach,"
			+ "    store_indent_approver1 AS store_indent_approver1,"
			+ "    store_indent_approver2 AS store_indent_approver2,"
			+ "    esi_no AS esi_no,"
			+ "    hra AS hra,"
			+ "    da AS da,"
			+ "    cca AS cca,"
			+ "    net_pay AS net_pay,"
			+ "    other_allow AS other_allow,"
			+ "    spl_1 AS spl_1,"
			+ "    title AS title,"
			+ "    caste_category AS caste_category,"
			+ "    school AS school,"
			+ "    contract_empcode AS contract_empcode,"
			+ "    consolidated_amount AS consolidated_amount,"
			+ "    from_date AS from_date,"
			+ "    date_of_joining AS date_of_joining,"
			+ "    remarks AS remarks,"
			+ "    subject_skills AS subject_skills,"
			+ "    employee_status AS employee_status,"
			+ "    proctor_type AS proctor_type,"
			+ "    chief_proctor_id AS chief_proctor_id,"
			+ "    religion AS religion,"
			+ "    preferred_name_for_email AS preferred_name_for_email,"
			+ "    emp_attachment_path AS emp_attachment_path,"
			+ "    emp_attachment_file_name AS emp_attachment_file_name,"
			+ "    emp_attachement_type AS emp_attachement_type,"
			+ "    emp_image_attachment_path AS emp_image_attachment_path,"
			+ "    phd_status AS phd_status,"
			+ "    salary_structure_email_content AS salary_structure_email_content,"
			+ "    pt AS pt,"
			+ "    visa_expiry_date AS visa_expiry_date,"
			+ "    visa_document_number AS visa_document_number,"
			+ "    nationality AS nationality,"
			+ "    place_of_birth AS place_of_birth,"
			+ "    language_id AS language_id,"
			+ "    personal_medical_history AS personal_medical_history,"
			+ "    family_medical_history AS family_medical_history,"
			+ "    emp_attachment_path2 AS emp_attachment_path2,"
			+ "    emp_attachment_file_name2 AS emp_attachment_file_name2,"
			+ "    emp_attachement_type2 AS emp_attachement_type2,"
			+ "    id_barcode_generated AS id_barcode_generated,"
			+ "    permanent_file AS permanent_file,"
			+ "    permanent_done_by AS permanent_done_by,"
			+ "    permanent_status AS permanent_status,"
			+ "    date_of_permanent AS date_of_permanent,"
			+ "    job_short_name AS job_short_name,"
			+ "    dept_name_short AS dept_name_short,"
			+ "    school_name_short AS school_name_short,"
			+ "    shift_name AS shift_name,"
			+ "    leave_approver1_name AS leave_approver1_name,"
			+ "    leave_approver2_name AS leave_approver2_name,"
			+ "    reportingOfficerName AS reportingOfficerName,"
			+ "    personal_email AS personal_email)"
			+ " from EmployeeDetailsHistory edh "
			+ "where edh.active=true And CONCAT(IfNull(edh.empcode,''),'',IfNull(edh.employee_name,''),'',IfNull(edh.preferred_name_for_email,''),' ',"
			+ "IfNull(edh.email,'')) LIKE %?1% and edh.emp_id=?2")
	public Page<Object> getAllDataFilteredByKeywordByEmpId(Pageable pageable, Object keyword, Integer emp_id); 
	
	@Query(value = "select new map(emp_history_id AS id,"
			+ "    emp_id AS emp_id,"
			+ "    school_id AS school_id,"
			+ "    dept_id AS dept_id,"
			+ "    job_id AS job_id,"
			+ "    email AS email,"
			+ "    employee_name AS employee_name,"
			+ "    created_date AS created_date,"
			+ "    created_by AS created_by,"
			+ "    created_username AS created_username,"
			+ "    active AS active,"
			+ "    master_code AS master_code,"
			+ "    empcode AS empcode,"
			+ "    firstname AS firstname,"
			+ "    lastname AS lastname,"
			+ "    report_id AS report_id,"
			+ "    mobile AS mobile,"
			+ "    alt_mobile_no AS alt_mobile_no,"
			+ "    dateofbirth AS dateofbirth,"
			+ "    martial_status AS martial_status,"
			+ "    blood_group AS blood_group,"
			+ "    designation_id AS designation_id,"
			+ "    father_name AS father_name,"
			+ "    spouse_name AS spouse_name,"
			+ "    current_location AS current_location,"
			+ "    salary_structure_id AS salary_structure_id,"
			+ "    ctc AS ctc,"
			+ "    pf_no AS pf_no,"
			+ "    pan_no AS pan_no,"
			+ "    emp_type_id AS emp_type_id,"
			+ "    job_type_id AS job_type_id,"
			+ "    hometown AS hometown,"
			+ "    pincode AS pincode,"
			+ "    annual_salary AS annual_salary,"
			+ "    spl_pay AS spl_pay,"
			+ "    key_skills AS key_skills,"
			+ "    bank_id AS bank_id,"
			+ "    bank_account_no AS bank_account_no,"
			+ "    bank_branch AS bank_branch,"
			+ "    bank_ifsccode AS bank_ifsccode,"
			+ "    leave_approver1_emp_id AS leave_approver1_emp_id,"
			+ "    leave_approver2_emp_id AS leave_approver2_emp_id,"
			+ "    attach AS attach,"
			+ "    dlno AS dlno,"
			+ "    dlexpno AS dlexpno,"
			+ "    passportno AS passportno,"
			+ "    passportexpno AS passportexpno,"
			+ "    bankacc2 AS bankacc2,"
			+ "    to_date AS to_date,"
			+ "    prob AS prob,"
			+ "    nda AS nda,"
			+ "    nca AS nca,"
			+ "    uan_no AS uan_no,"
			+ "    punched_card_status AS punched_card_status,"
			+ "    photo AS photo,"
			+ "    shift_category_id AS shift_category_id,"
			+ "    gender AS gender,"
			+ "    maternity_status AS maternity_status,"
			+ "    marriage_status AS marriage_status,"
			+ "    paternity_status AS paternity_status,"
			+ "    salary_approve_status AS salary_approve_status,"
			+ "    new_join_status AS new_join_status,"
			+ "    pf_status AS pf_status,"
			+ "    pt_status AS pt_status,"
			+ "    permanant_file AS permanant_file,"
			+ "    aadhar AS aadhar,"
			+ "    photo_upload_status AS photo_upload_status,"
			+ "    proctor_assign_status AS proctor_assign_status,"
			+ "    bank_account_holder_name AS bank_account_holder_name,"
			+ "    grosspay_ctc AS grosspay_ctc,"
			+ "    nda_nca_attach AS nda_nca_attach,"
			+ "    store_indent_approver1 AS store_indent_approver1,"
			+ "    store_indent_approver2 AS store_indent_approver2,"
			+ "    esi_no AS esi_no,"
			+ "    hra AS hra,"
			+ "    da AS da,"
			+ "    cca AS cca,"
			+ "    net_pay AS net_pay,"
			+ "    other_allow AS other_allow,"
			+ "    spl_1 AS spl_1,"
			+ "    title AS title,"
			+ "    caste_category AS caste_category,"
			+ "    school AS school,"
			+ "    contract_empcode AS contract_empcode,"
			+ "    consolidated_amount AS consolidated_amount,"
			+ "    from_date AS from_date,"
			+ "    date_of_joining AS date_of_joining,"
			+ "    remarks AS remarks,"
			+ "    subject_skills AS subject_skills,"
			+ "    employee_status AS employee_status,"
			+ "    proctor_type AS proctor_type,"
			+ "    chief_proctor_id AS chief_proctor_id,"
			+ "    religion AS religion,"
			+ "    preferred_name_for_email AS preferred_name_for_email,"
			+ "    emp_attachment_path AS emp_attachment_path,"
			+ "    emp_attachment_file_name AS emp_attachment_file_name,"
			+ "    emp_attachement_type AS emp_attachement_type,"
			+ "    emp_image_attachment_path AS emp_image_attachment_path,"
			+ "    phd_status AS phd_status,"
			+ "    salary_structure_email_content AS salary_structure_email_content,"
			+ "    pt AS pt,"
			+ "    visa_expiry_date AS visa_expiry_date,"
			+ "    visa_document_number AS visa_document_number,"
			+ "    nationality AS nationality,"
			+ "    place_of_birth AS place_of_birth,"
			+ "    language_id AS language_id,"
			+ "    personal_medical_history AS personal_medical_history,"
			+ "    family_medical_history AS family_medical_history,"
			+ "    emp_attachment_path2 AS emp_attachment_path2,"
			+ "    emp_attachment_file_name2 AS emp_attachment_file_name2,"
			+ "    emp_attachement_type2 AS emp_attachement_type2,"
			+ "    id_barcode_generated AS id_barcode_generated,"
			+ "    permanent_file AS permanent_file,"
			+ "    permanent_done_by AS permanent_done_by,"
			+ "    permanent_status AS permanent_status,"
			+ "    date_of_permanent AS date_of_permanent,"
			+ "    job_short_name AS job_short_name,"
			+ "    dept_name_short AS dept_name_short,"
			+ "    school_name_short AS school_name_short,"
			+ "    shift_name AS shift_name,"
			+ "    leave_approver1_name AS leave_approver1_name,"
			+ "    leave_approver2_name AS leave_approver2_name,"
			+ "    reportingOfficerName AS reportingOfficerName,"
			+ "    personal_email AS personal_email)"
			+ " from EmployeeDetailsHistory edh where edh.emp_id=?1")
	public Page<Object> getAllSortedDataByEmpId(Pageable pageable, Integer emp_id);


}
